`app` is not defined
Forgot to import app form electron
```js
ReferenceError: app is not defined
    at Timeout._onTimeout (/Users/runner/work/shinyElectron/shinyElectron/test/platform.js:18:4)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```